fixed set-output warning in github actions, upgraded @actions/core to 1.10.0
neuvector/scan-action pull request #3
Opened 2022-11-25 07:56 UTC by rajeshkio

2022-11-25 08:41 UTC, bashofmann requested changes
I don't think the change for `::set-output` is correct.

According to the docs https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter it should be something like 

```
echo "medium_vulnerability_count=${FOUND_MEDIUM}" >> $GITHUB_OUTPUT
```

2022-11-25 14:31 UTC, bashofmann approved these changes

2022-11-25 14:32 UTC, rajeshkio commented
> I don't think the change for `::set-output` is correct.
> 
> According to the docs https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter it should be something like
> 
> ```
> echo "medium_vulnerability_count=${FOUND_MEDIUM}" >> $GITHUB_OUTPUT
> ```
Fixed. Thank you.

2024-03-21 00:57 UTC, becitsthere commented
This patch has been incorporated into the repo

2024-03-21 00:57 UTC, closed without merging